### ISSUE TITLE
Treebase stopped working and now I cannot log in

### ISSUE THREAD

**Issue by cynanchum** [TreeBASE/treebase#277]
In the middle of painfully adding uBio numbers to my taxa, the program crashed and since then I can no more log in.

**Comment by fabrimafe** [comment]
Same problem here. It is a few days that is impossible to retrieve data.

**Comment by rvosa** [comment]
Apologies for the trouble you are having. Can you describe the symptoms in slightly more detail? The web application is online and I am able to download data but maybe I am clicking different buttons.

**Comment by fabrimafe** [comment]
Dear Rutger, for a couple of days Treebase was working a bit erratically: I was able to do normal searches and then it would stop working. To check, I was trying both via the R package or via browser. Since yesterday evening I did not encounter any more problems and I was able to download everything I needed. Probably it was just the server or something like this. Thanks!

**Comment by rvosa** [comment]
ok, good to know. Over time, the performance of the web application degrades because its temp folders fill up and because it hangs on certain queries. The thing we then do is simply reboot it. Perhaps you just caught it in a downward spiral.

**Comment by ordynets** [comment]
I also cannot search studies by ID (e.g. my own 22473, was working well in 2018-2019) and cannot log in. Tried now in Firefox 94.0.1 (64-Bit), Chrome 95.0.4638.69 (64-Bit), and Microsoft Edge 95.0.1020.44(64-Bit).

**Comment by rvosa** [comment]
We aware of the problems. Whether they can be addressed is being investigated. Right now the project lacks resources for full time programmer support, which is needed.
